### ISSUE TITLE
cortex-m33 and stm32l5 support

### ISSUE THREAD

**Issue by Nukersson** [zephyrproject-rtos/openocd#35]
Hello together. I have following questions to active contributors / experts of this project:

1. Is there Cortex-M33 support already present? 
    1.1 What is your integration time estimation?
2. Is there stm32l5 support already present @ABOSTM @galak ?
    2.1 What is your integration time estimation?

Maybe these are trivial questions, but I would like to know answers, cause I am note an active participant of this project.

Thank you very much.

**Comment by ABOSTM** [comment]
@Nukersson ,
STM32L5 is not yet supported by official openOCD.
There is a patch available for that in gerrit: 
http://openocd.zylin.com/#/c/5510/5
Patch is open ... since march and still not merged.
I cannot provide you estimation as we depend on this patch to be merged, and I have no idea when this will be done.

**Comment by Nukersson** [comment]
> @Nukersson ,
> STM32L5 is not yet supported by official openOCD.
> There is a patch available for that in gerrit: 
> http://openocd.zylin.com/#/c/5510/5
> Patch is open ... since march and still not merged.
> I cannot provide you estimation as we depend on this patch to be merged, and I have no idea when this will be done.

Thank you for pointing on it.

**Comment by galak** [comment]
Closing as waiting on upstream to accept patch for STM32L5 support.
